import type { FormData } from '../schemas/brief-schema';

export interface Template {
  id: string;
  name: string;
  description: string;
  category: string;
  icon: string;
  data: Partial<FormData>;
}

export const templates: Template[] = [
  {
    id: 'commercial-product',
    name: 'Commercial Product Photography',
    description: 'Perfect for e-commerce, catalog, and product marketing shoots',
    category: 'Commercial',
    icon: '📦',
    data: {
      projectType: 'Commercial Product Photography',
      overview: 'Professional product photography for commercial use, focusing on high-quality imagery that showcases products in their best light.',
      objectives: '• Create clean, professional product images\n• Highlight key features and details\n• Maintain consistent lighting and background\n• Deliver images suitable for e-commerce and marketing',
      audience: 'Online shoppers, retail customers, B2B buyers',
      deliverables: ['photography', 'socialAssets'],
      fileTypes: ['jpeg', 'tiff', 'psd'],
      usageRights: ['website', 'social', 'advertising'],
      socialPlatforms: ['igFeed', 'facebookPost'],
      shotList: [
        {
          id: Date.now() + 1,
          description: 'Hero shot - product on white background, straight-on angle',
          shotType: 'Medium',
          angle: 'Eye-level',
          priority: true,
          notes: 'Key shot for homepage and main product page',
          category: 'Hero',
          equipment: ['White backdrop', 'Softbox lighting', 'Reflectors'],
          order: 1,
        },
        {
          id: Date.now() + 2,
          description: 'Detail shot - close-up of key product feature',
          shotType: 'Close-up',
          angle: 'Eye-level',
          priority: true,
          notes: 'Focus on texture, quality, craftsmanship',
          category: 'Details',
          equipment: ['Macro lens', 'Diffused lighting'],
          order: 2,
        },
        {
          id: Date.now() + 3,
          description: 'Lifestyle context - product in use or styled setting',
          shotType: 'Medium',
          angle: 'Eye-level',
          priority: false,
          notes: 'Show product in real-world context',
          category: 'Lifestyle',
          equipment: ['Props', 'Natural lighting setup'],
          order: 3,
        },
        {
          id: Date.now() + 4,
          description: 'Scale reference - product with size comparison',
          shotType: 'Medium',
          angle: 'Eye-level',
          priority: false,
          notes: 'Help customers understand product dimensions',
          category: 'Details',
          order: 4,
        },
      ],
      equipment: [
        { id: '1', name: 'DSLR/Mirrorless Camera', category: 'Camera', quantity: 1, isRental: false, checked: false },
        { id: '2', name: '24-70mm f/2.8 Lens', category: 'Lens', quantity: 1, isRental: false, checked: false },
        { id: '3', name: 'Macro Lens 100mm', category: 'Lens', quantity: 1, isRental: false, checked: false },
        { id: '4', name: 'Softbox Kit (2x)', category: 'Lighting', quantity: 1, isRental: false, checked: false },
        { id: '5', name: 'White Backdrop', category: 'Grip', quantity: 1, isRental: false, checked: false },
        { id: '6', name: 'Reflector Set', category: 'Lighting', quantity: 1, isRental: false, checked: false },
      ],
    },
  },
  {
    id: 'corporate-events',
    name: 'Corporate Event Coverage',
    description: 'Conferences, meetings, team events, and corporate gatherings',
    category: 'Corporate',
    icon: '🏢',
    data: {
      projectType: 'Corporate Event Photography',
      overview: 'Comprehensive event coverage capturing key moments, speakers, attendees, and venue atmosphere for corporate communications and marketing.',
      objectives: '• Document key speakers and presentations\n• Capture candid attendee interactions\n• Photograph venue and branding elements\n• Create a visual story of the event',
      audience: 'Employees, stakeholders, potential clients, social media followers',
      deliverables: ['photography', 'socialAssets'],
      fileTypes: ['jpeg', 'tiff'],
      usageRights: ['website', 'social', 'internal'],
      socialPlatforms: ['igFeed', 'igStory', 'linkedinPost'],
      shotList: [
        {
          id: Date.now() + 1,
          description: 'Wide shot - full venue with attendees',
          shotType: 'Wide',
          angle: 'High Angle',
          priority: true,
          notes: 'Establish shot showing scale and atmosphere',
          category: 'Venue',
          order: 1,
        },
        {
          id: Date.now() + 2,
          description: 'Keynote speaker at podium',
          shotType: 'Medium',
          angle: 'Eye-level',
          priority: true,
          notes: 'Multiple angles, capture gestures and expressions',
          category: 'Speakers',
          order: 2,
        },
        {
          id: Date.now() + 3,
          description: 'Attendee candids - networking and engagement',
          shotType: 'Medium',
          angle: 'Eye-level',
          priority: true,
          notes: 'Natural interactions, smiling faces',
          category: 'Attendees',
          order: 3,
        },
        {
          id: Date.now() + 4,
          description: 'Detail shots - branding, signage, materials',
          shotType: 'Close-up',
          angle: 'Eye-level',
          priority: false,
          notes: 'Capture corporate identity elements',
          category: 'Details',
          order: 4,
        },
      ],
      equipment: [
        { id: '1', name: 'Two Camera Bodies', category: 'Camera', quantity: 2, isRental: false, checked: false },
        { id: '2', name: '24-70mm f/2.8', category: 'Lens', quantity: 1, isRental: false, checked: false },
        { id: '3', name: '70-200mm f/2.8', category: 'Lens', quantity: 1, isRental: false, checked: false },
        { id: '4', name: 'External Flash', category: 'Lighting', quantity: 1, isRental: false, checked: false },
        { id: '5', name: 'Extra Batteries & Memory Cards', category: 'Camera', quantity: 5, isRental: false, checked: false },
      ],
    },
  },
  {
    id: 'food-beverage',
    name: 'Food & Beverage Photography',
    description: 'Restaurant menus, cookbooks, food brands, and culinary content',
    category: 'Food',
    icon: '🍽️',
    data: {
      projectType: 'Food & Beverage Photography',
      overview: 'Mouth-watering food photography that showcases dishes and beverages in the most appetizing way, perfect for menus, marketing, and editorial use.',
      objectives: '• Make food look fresh, delicious, and appealing\n• Capture texture, color, and presentation\n• Tell a culinary story through imagery\n• Maintain brand consistency',
      audience: 'Restaurant guests, food enthusiasts, social media followers',
      deliverables: ['photography', 'socialAssets'],
      fileTypes: ['jpeg', 'tiff', 'psd'],
      usageRights: ['website', 'social', 'print'],
      socialPlatforms: ['igFeed', 'igStory', 'facebookPost'],
      shotList: [
        {
          id: Date.now() + 1,
          description: 'Hero shot - signature dish, overhead angle',
          shotType: 'Overhead',
          angle: 'High Angle',
          priority: true,
          notes: 'Perfect plating, garnish fresh, steam if hot dish',
          category: 'Hero',
          equipment: ['Overhead rig', 'Natural light diffusion', 'Food styling props'],
          order: 1,
        },
        {
          id: Date.now() + 2,
          description: '45-degree angle - shows depth and layers',
          shotType: 'Medium',
          angle: 'High Angle',
          priority: true,
          notes: 'Classic food photography angle, shows dimension',
          category: 'Hero',
          equipment: ['Side lighting', 'Reflector'],
          order: 2,
        },
        {
          id: Date.now() + 3,
          description: 'Close-up detail - texture and ingredients',
          shotType: 'Close-up',
          angle: 'Eye-level',
          priority: false,
          notes: 'Highlight fresh ingredients, sauce drizzle, garnish',
          category: 'Details',
          equipment: ['Macro lens', 'Diffused flash'],
          order: 3,
        },
        {
          id: Date.now() + 4,
          description: 'Table scene - multiple dishes styled together',
          shotType: 'Wide',
          angle: 'High Angle',
          priority: false,
          notes: 'Create an inviting dining scene',
          category: 'Lifestyle',
          equipment: ['Props', 'Linens', 'Natural lighting'],
          order: 4,
        },
      ],
      equipment: [
        { id: '1', name: 'Full-Frame Camera', category: 'Camera', quantity: 1, isRental: false, checked: false },
        { id: '2', name: '50mm f/1.4 or 1.8', category: 'Lens', quantity: 1, isRental: false, checked: false },
        { id: '3', name: '100mm Macro', category: 'Lens', quantity: 1, isRental: false, checked: false },
        { id: '4', name: 'Natural Light Diffusion', category: 'Lighting', quantity: 1, isRental: false, checked: false },
        { id: '5', name: 'Reflectors', category: 'Lighting', quantity: 1, isRental: false, checked: false },
        { id: '6', name: 'Food Styling Kit', category: 'Props', quantity: 1, isRental: false, checked: false },
        { id: '7', name: 'Backdrop & Surface Options', category: 'Props', quantity: 1, isRental: false, checked: false },
      ],
      notes: 'Food stylist recommended for best results. All dishes should be prepped immediately before shooting for maximum freshness.',
    },
  },
  {
    id: 'fashion-editorial',
    name: 'Fashion & Editorial',
    description: 'Fashion campaigns, lookbooks, editorial shoots, and style content',
    category: 'Fashion',
    icon: '👗',
    data: {
      projectType: 'Fashion & Editorial Photography',
      overview: 'High-impact fashion photography showcasing clothing, accessories, and style through creative composition and lighting.',
      objectives: '• Showcase garments and styling\n• Create aspirational, on-brand imagery\n• Capture mood and aesthetic direction\n• Highlight design details and fit',
      audience: 'Fashion consumers, brand followers, editorial readers',
      deliverables: ['photography', 'socialAssets'],
      fileTypes: ['jpeg', 'tiff', 'psd'],
      usageRights: ['website', 'social', 'advertising', 'print'],
      socialPlatforms: ['igFeed', 'igStory', 'facebookPost'],
      shotList: [
        {
          id: Date.now() + 1,
          description: 'Full-length shot - complete look and styling',
          shotType: 'Wide',
          angle: 'Eye-level',
          priority: true,
          notes: 'Show proportions, full outfit, styled head to toe',
          category: 'Hero',
          order: 1,
        },
        {
          id: Date.now() + 2,
          description: 'Three-quarter shot - focus on garment details',
          shotType: 'Medium',
          angle: 'Eye-level',
          priority: true,
          notes: 'Capture fit, drape, and texture',
          category: 'Details',
          order: 2,
        },
        {
          id: Date.now() + 3,
          description: 'Close-up - fabric texture, buttons, embellishments',
          shotType: 'Close-up',
          angle: 'Eye-level',
          priority: false,
          notes: 'Highlight craftsmanship and quality',
          category: 'Details',
          order: 3,
        },
        {
          id: Date.now() + 4,
          description: 'Movement shot - garment in motion',
          shotType: 'Medium',
          angle: 'Eye-level',
          priority: false,
          notes: 'Capture flow, movement, energy',
          category: 'Action',
          order: 4,
        },
      ],
      equipment: [
        { id: '1', name: 'Full-Frame Camera', category: 'Camera', quantity: 1, isRental: false, checked: false },
        { id: '2', name: '24-70mm f/2.8', category: 'Lens', quantity: 1, isRental: false, checked: false },
        { id: '3', name: '85mm f/1.4', category: 'Lens', quantity: 1, isRental: false, checked: false },
        { id: '4', name: 'Strobe Lighting Kit', category: 'Lighting', quantity: 1, isRental: false, checked: false },
        { id: '5', name: 'Backdrop & Stands', category: 'Grip', quantity: 1, isRental: false, checked: false },
      ],
      crew: [
        { id: Date.now() + 1, name: 'Model', role: 'Talent', callTime: '09:00', contact: 'TBD' },
        { id: Date.now() + 2, name: 'Hair & Makeup Artist', role: 'Styling', callTime: '08:00', contact: 'TBD' },
        { id: Date.now() + 3, name: 'Fashion Stylist', role: 'Styling', callTime: '08:30', contact: 'TBD' },
      ],
    },
  },
  {
    id: 'real-estate',
    name: 'Real Estate & Architectural',
    description: 'Property listings, architectural photography, interior design',
    category: 'Real Estate',
    icon: '🏠',
    data: {
      projectType: 'Real Estate & Architectural Photography',
      overview: 'Professional property photography showcasing spaces at their best, highlighting architecture, design, and livability for real estate marketing.',
      objectives: '• Capture spaciousness and natural light\n• Showcase key features and upgrades\n• Create inviting, aspirational imagery\n• Maintain vertical lines and perspective',
      audience: 'Home buyers, renters, real estate investors',
      deliverables: ['photography'],
      fileTypes: ['jpeg', 'tiff'],
      usageRights: ['website', 'social', 'print'],
      socialPlatforms: ['igFeed', 'facebookPost'],
      shotList: [
        {
          id: Date.now() + 1,
          description: 'Exterior - front facade at golden hour',
          shotType: 'Wide',
          angle: 'Eye-level',
          priority: true,
          notes: 'Best light 30 mins before sunset, show curb appeal',
          category: 'Exterior',
          equipment: ['Wide-angle lens', 'Tripod', 'ND filters'],
          order: 1,
        },
        {
          id: Date.now() + 2,
          description: 'Living room - wide angle showing space flow',
          shotType: 'Wide',
          angle: 'Eye-level',
          priority: true,
          notes: 'All lights on, windows visible, decluttered',
          category: 'Interior',
          equipment: ['16-35mm lens', 'Tripod', 'Flash for ambient blend'],
          order: 2,
        },
        {
          id: Date.now() + 3,
          description: 'Kitchen - highlight counters, appliances, storage',
          shotType: 'Wide',
          angle: 'Eye-level',
          priority: true,
          notes: 'Clean surfaces, staged with minimal styling',
          category: 'Interior',
          order: 3,
        },
        {
          id: Date.now() + 4,
          description: 'Master bedroom - inviting, spacious',
          shotType: 'Wide',
          angle: 'Eye-level',
          priority: false,
          notes: 'Bed made, natural light, show closet if notable',
          category: 'Interior',
          order: 4,
        },
        {
          id: Date.now() + 5,
          description: 'Backyard/outdoor space',
          shotType: 'Wide',
          angle: 'Eye-level',
          priority: false,
          notes: 'Show usable outdoor living space',
          category: 'Exterior',
          order: 5,
        },
      ],
      equipment: [
        { id: '1', name: 'Full-Frame Camera', category: 'Camera', quantity: 1, isRental: false, checked: false },
        { id: '2', name: '16-35mm f/4', category: 'Lens', quantity: 1, isRental: false, checked: false },
        { id: '3', name: 'Tripod', category: 'Grip', quantity: 1, isRental: false, checked: false },
        { id: '4', name: 'External Flash', category: 'Lighting', quantity: 1, isRental: false, checked: false },
        { id: '5', name: 'Tilt-Shift Lens (optional)', category: 'Lens', quantity: 1, isRental: true, checked: false },
      ],
      notes: 'Property should be cleaned and staged before shoot. All lights should be turned on. Best shooting times: 10am-2pm for interiors, golden hour for exteriors.',
    },
  },
  {
    id: 'wedding-lifestyle',
    name: 'Wedding & Lifestyle',
    description: 'Weddings, engagements, family portraits, lifestyle sessions',
    category: 'Lifestyle',
    icon: '💒',
    data: {
      projectType: 'Wedding & Lifestyle Photography',
      overview: 'Emotional, candid, and artful coverage of life\'s special moments, capturing authentic connections and memorable experiences.',
      objectives: '• Capture genuine emotions and connections\n• Document key moments and details\n• Create timeless, artistic imagery\n• Tell the story of the day',
      audience: 'Couple, family members, wedding guests',
      deliverables: ['photography', 'socialAssets'],
      fileTypes: ['jpeg', 'tiff'],
      usageRights: ['personal', 'social'],
      socialPlatforms: ['igFeed', 'igStory', 'facebookPost'],
      shotList: [
        {
          id: Date.now() + 1,
          description: 'Getting ready - candid preparations',
          shotType: 'Medium',
          angle: 'Eye-level',
          priority: true,
          notes: 'Details, emotions, interactions with bridal party',
          category: 'Prep',
          order: 1,
        },
        {
          id: Date.now() + 2,
          description: 'First look - emotional moment',
          shotType: 'Medium',
          angle: 'Eye-level',
          priority: true,
          notes: 'Capture raw emotion, multiple angles',
          category: 'Moments',
          order: 2,
        },
        {
          id: Date.now() + 3,
          description: 'Ceremony - vows and key moments',
          shotType: 'Medium',
          angle: 'Eye-level',
          priority: true,
          notes: 'Multiple angles, reactions, first kiss',
          category: 'Ceremony',
          order: 3,
        },
        {
          id: Date.now() + 4,
          description: 'Couple portraits - romantic, intimate',
          shotType: 'Medium',
          angle: 'Eye-level',
          priority: true,
          notes: 'Golden hour preferred, various poses and moments',
          category: 'Portraits',
          order: 4,
        },
        {
          id: Date.now() + 5,
          description: 'Reception - dancing, toasts, candids',
          shotType: 'Medium',
          angle: 'Eye-level',
          priority: true,
          notes: 'Capture energy and celebration',
          category: 'Reception',
          order: 5,
        },
      ],
      equipment: [
        { id: '1', name: 'Two Camera Bodies', category: 'Camera', quantity: 2, isRental: false, checked: false },
        { id: '2', name: '24-70mm f/2.8', category: 'Lens', quantity: 1, isRental: false, checked: false },
        { id: '3', name: '70-200mm f/2.8', category: 'Lens', quantity: 1, isRental: false, checked: false },
        { id: '4', name: '35mm f/1.4', category: 'Lens', quantity: 1, isRental: false, checked: false },
        { id: '5', name: 'External Flash', category: 'Lighting', quantity: 2, isRental: false, checked: false },
        { id: '6', name: 'Extra Batteries & Cards', category: 'Camera', quantity: 10, isRental: false, checked: false },
      ],
      crew: [
        { id: Date.now() + 1, name: 'Second Shooter', role: 'Photography', callTime: '10:00', contact: 'TBD' },
      ],
      notes: 'Timeline critical - coordinate with wedding planner. Backup equipment essential. Scout venue in advance if possible.',
    },
  },
];

export function getTemplateById(id: string): Template | undefined {
  return templates.find((t) => t.id === id);
}

export function getTemplatesByCategory(category: string): Template[] {
  return templates.filter((t) => t.category === category);
}

export function getAllCategories(): string[] {
  return Array.from(new Set(templates.map((t) => t.category)));
}
